version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: e-gov-dev-env
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: 1234qwer
      POSTGRES_DB: e-gov-db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
