version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    container_name: e-gov-dev-env
    environment:
      POSTGRES_DB: e-gov-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234qwer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


