version: "3.8"

services:
  database:
    container_name: e-gov-postgres
    build:
      context: ../../e-gov-dev-env
      dockerfile: ../Dockerfile
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234qwer
        POSTGRES_DB: e-gov-db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    container_name: e-gov-react
    build:
      context: ../../e-gov-frontend
      dockerfile: ../e-gov-frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    container_name: e-gov-spring-boot
    build:
      context: ../../e-gov-backend
      dockerfile: ../e-gov-backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234qwer


volumes:
  postgres_data:
