name: Deployment Workflow

on:
  push:
    branches:
      - feature/DB-006.5

jobs:
  deploy:
    runs-on: ubuntu-22.04.4
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate API Keys
        run: |
          openssl ecparam -name prime256v1 -genkey -out private.pem
          openssl ec -in private.pem -pubout -out public.pem

      - name: Download requirements
        run: pip install -r requirements.txt

      - name: Start docker compose
        run: python manage.py start

